---
title: "TUTORIAL PARA GENERAR REPORTE ESTATUS Y CBA PELÁGICOS CENTRO-SUR"
author: "María José Zúñiga"
date: '`r format(Sys.Date(),"Última actualización: %B, %d, %Y")`'
output: 
  pdf_document:
   toc: TRUE
   number_sections: yes
---

\pagebreak

```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=T, warning=FALSE, message=FALSE,fig.align="center",fig.pos="h!")
```

# Librerías requeridas
```{r}
library(stringr) # para arreglo de archivo .dat
library(tidyverse)
library(kableExtra) # genera tablas
library(ggplot2) # genera figuras
library(ggthemes) # para ggplot
library(patchwork) # para unir gráficos de ggplot
library(dplyr)  # para usar melt
library(reshape) # para usar melt
library(here)
```

# Directorios de trabajo
```{r}
dir.0   <- here() 
dir.1   <- paste(dir.0,"/codigos_admb",sep="") 
dir.fun <- paste(dir.0,"/funciones/",sep="") 
dir.Rdata<-paste(dir.0,"/Rdata/",sep="")

```

# Funciones utilizadas
```{r}
source(paste(dir.fun,"functions.R",sep="")) 
source(paste(dir.fun,"Fn_CrearRdata.R",sep=""))
source(paste(dir.fun,"Fn_Data.frame.R",sep=""))
source(paste(dir.fun,"Fn_Figuras.R",sep=""))
source(paste(dir.fun,"Fn_Tablas.R",sep=""))
```

# `Fn_CrearRdata.R`
```{r}
setwd(dir.1)

admb_dat  <- list.files(pattern=".dat")
admb_rep  <- list.files(pattern=".rep")
admb_std  <- list.files(pattern=".std")

CreaRdata(admb_dat[3],admb_rep[3],admb_std[3],'Hito1',dir.Rdata)
CreaRdata(admb_dat[1],admb_rep[1],admb_std[1],'Hito2',dir.Rdata)
CreaRdata(admb_dat[2],admb_rep[2],admb_std[2],'Hito3',dir.Rdata)

```

\pagebreak

# `Fn_Data.frame.R`

## `indobs_Fig1` 
```{r}
indobs_H2<-indobs_Fig1(archivo.Rdata='DatosHito2.RData',Hitoasesoria='Hito2')

```

## `indpred_Fig1`
```{r}
indpred_H2<-indpred_Fig1(archivo.Rdata='DatosHito2.RData',Hitoasesoria='Hito2')
indpred_H1<-indpred_Fig1(archivo.Rdata='DatosHito1.RData',Hitoasesoria='Hito1')
```

## `resind_Fig2`
```{r}
Res_H2<-resind_Fig2(indobs_H2,indpred_H2)
```

\pagebreak

# `Fn_Tablas.R`

## `tb1`

```{r}

tb1('DatosHito2.RData')

```

## `tb2`

```{r}
yearsb  <- c("1996/97","1997/98","1998/99","1999/00","2000/01","2001/02","2002/03",
               "2003/04","2004/05","2005/06","2006/07","2007/08","2008/09","2009/10",
               "2010/11","2011/12","2012/13","2013/14","2014/15","2015/16","2016/17",
               "2017/18","2018/19","2019/20",'2020/21','2021/22','2022/23')

bioyear<-yearsb
desemYdesc_previo<-c(350755,77701,442110,56441,14545,235359,
                     269955,359681,431902,328805,639364,411747,
                     362871,311530,167758,66681,60226,58785,
                     57116,71774,51957,67425,138520,160799,209506,203330,NA)

desc_previo       <- c(rep(1,4),rep(1.04,15),rep(1.02,1),rep(1.06,1),1.01,rep(1.02,5))
desembarque       <- desemYdesc_previo/desc_previo
desc_actualizado  <- c(rep(1,4),rep(1.04,17),1.014,1.021,1.018,1.02,1.02,1.02)
CapturaDescartada <- -(1-desc_actualizado)*desembarque
CapturaTotal      <- desembarque+CapturaDescartada

porcDesc_actualizado<-c(rep("0\\%",4),rep("4\\%",17),rep("1,4\\%",1),rep("2,1\\%",1),rep("1,8\\%",1),rep("2\\%",3))


tb2(bioyear,desembarque,porcDesc_actualizado,CapturaDescartada,CapturaTotal)

```

\pagebreak

# `Fn_Figuras.R`

## `fig1.0`
```{r fig.height=6.5,fig.width=5}
 
fig1.0('DatosHito2.RData')
 
```

## `fig2.0`
```{r Fig18,fig.height=4,fig.width=9}

fig2.0('DatosHito2.RData')

```

## `fig3.0`
```{r fig.height=6,fig.width=9}

fig3.0('DatosHito2.RData')    

```

## `fig4.0`
```{r fig.height=4,fig.width=9}

fig4.0('DatosHito2.RData')

```

## `fig5.0`
```{r fig.height=6,fig.width=9}

fig5.0('DatosHito2.RData')

```


## `fig1` 
```{r fig.height=7,fig.width=8}

base1<-merge(indobs_H2, merge(indpred_H1, indpred_H2, all = TRUE), all = TRUE)  

fig1(base1)

```


## `fig2`
```{r fig.height=5.7,fig.width=6.5}

fig2(Res_H2)

```


